import { Team } from "./team";

// Generated by https://quicktype.io

export interface Game {
    id:                 number;
    date:               string;
    home_team_score:    number;
    visitor_team_score: number;
    season:             number;
    period:             number;
    status:             string;
    time:               string;
    postseason:         boolean;
    home_team:          Team;
    visitor_team:       Team;
}
