// Generated by https://quicktype.io

export interface BallDontLieResponse<T> {
    data: T;
    meta: Meta;
}

export interface Meta {
    total_pages:  number;
    current_page: number;
    next_page:    number;
    per_page:     number;
    total_count:  number;
}
