// Generated by https://quicktype.io

/**
 * Response type from the balldontlie API. Meta contains pagination information
 * for APIs that return lists of data.
 *
 * @export
 * @interface BallDontLieResponse
 * @template T
 */
export interface BallDontLieResponse<T> {
    data: T;
    meta: Meta;
}

/**
 * Metadata containing pagination information.
 *
 * @export
 * @interface Meta
 */
export interface Meta {
    total_pages:  number;
    current_page: number;
    next_page:    number;
    per_page:     number;
    total_count:  number;
}
