// Generated by https://quicktype.io

export interface SeasonAverages {
    games_played: number;
    player_id:    number;
    season:       number;
    min:          string;
    fgm:          number;
    fga:          number;
    fg3m:         number;
    fg3a:         number;
    ftm:          number;
    fta:          number;
    oreb:         number;
    dreb:         number;
    reb:          number;
    ast:          number;
    stl:          number;
    blk:          number;
    turnover:     number;
    pf:           number;
    pts:          number;
    fg_pct:       number;
    fg3_pct:      number;
    ft_pct:       number;
}
