// Generated by https://quicktype.io

export interface Team {
    id:           number;
    abbreviation: string;
    city:         string;
    conference:   string;
    division:     string;
    full_name:    string;
    name:         string;
}
