// Generated by https://quicktype.io

/**
 * A team in the NBA.
 *
 * @export
 * @interface Team
 */
export interface Team {
    id:           number;
    abbreviation: string;
    city:         string;
    conference:   string;
    division:     string;
    full_name:    string;
    name:         string;
}
